/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Parte1.Cliente;
import javax.swing.JTextField;

/**
 *
 * @author ediso
 */
public class ConsultasAeropuerto extends javax.swing.JFrame {

    Cliente cliente;

    /**
     * Creates new form ConsultasAeropuerto
     */
    public ConsultasAeropuerto() {
        initComponents();
        cliente = new Cliente(jTextFieldAeroviaBarcelona_Madrid, jTextFieldAeroviaMadrid_Barcelona, jTextFieldAvionesAreaEstacionamientoBarcelona, jTextFieldAvionesAreaEstacionamientoMadrid, jTextFieldAvionesAreaRodajeBarcelona, jTextFieldAvionesAreaRodajeMadrid, jTextFieldAvionesHangarBarcelona, jTextFieldAvionesHangarMadrid, jTextFieldAvionesTallerBarcelona, jTextFieldAvionesTallerMadrid, jTextFieldPasajerosAeropuertoBarcelona, jTextFieldPasajerosAeropuertoMadrid);
        cliente.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPasajerosAeropuertoMadrid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAvionesHangarMadrid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAvionesTallerMadrid = new javax.swing.JTextField();
        jTextFieldAvionesAreaEstacionamientoMadrid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAvionesAreaRodajeMadrid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonCerrarPista1Madrid = new javax.swing.JButton();
        jButtonAbrirPista1Madrid = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonCerrarPista2Madrid = new javax.swing.JButton();
        jButtonAbrirPista2Madrid = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonCerrarPista3Madrid = new javax.swing.JButton();
        jButtonAbrirPista3Madrid = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtonCerrarPista4Madrid = new javax.swing.JButton();
        jButtonAbrirPista4Madrid = new javax.swing.JButton();
        jTextFieldAeroviaBarcelona_Madrid = new javax.swing.JTextField();
        jTextFieldAeroviaMadrid_Barcelona = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButtonCerrarPista4Barcelona = new javax.swing.JButton();
        jButtonAbrirPista4Barcelona = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPasajerosAeropuertoBarcelona = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldAvionesHangarBarcelona = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldAvionesTallerBarcelona = new javax.swing.JTextField();
        jTextFieldAvionesAreaEstacionamientoBarcelona = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldAvionesAreaRodajeBarcelona = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButtonCerrarPista1Barcelona = new javax.swing.JButton();
        jButtonAbrirPista1Barcelona = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButtonCerrarPista2Barcelona = new javax.swing.JButton();
        jButtonAbrirPista2Barcelona = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButtonCerrarPista3Barcelona = new javax.swing.JButton();
        jButtonAbrirPista3Barcelona = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AEROPUERTO DE MADRID");

        jLabel2.setText("AEROPUERTO DE BARCELONA");

        jLabel3.setText("Nº Pasajeros en Aeropuerto:");

        jTextFieldPasajerosAeropuertoMadrid.setEditable(false);

        jLabel4.setText("Nº Aviones en Hangar:");

        jTextFieldAvionesHangarMadrid.setEditable(false);

        jLabel5.setText("Nº Aviones en Taller:");

        jTextFieldAvionesTallerMadrid.setEditable(false);

        jTextFieldAvionesAreaEstacionamientoMadrid.setEditable(false);

        jLabel6.setText("Nº Aviones en Area de Estacionamiento:");

        jTextFieldAvionesAreaRodajeMadrid.setEditable(false);

        jLabel7.setText("Nº Aviones en Area de Rodaje:");

        jLabel8.setText("Pista 1");

        jButtonCerrarPista1Madrid.setText("Cerrar");
        jButtonCerrarPista1Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPista1MadridActionPerformed(evt);
            }
        });

        jButtonAbrirPista1Madrid.setText("Abrir");
        jButtonAbrirPista1Madrid.setEnabled(false);
        jButtonAbrirPista1Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPista1MadridActionPerformed(evt);
            }
        });

        jLabel9.setText("Pista 2");

        jButtonCerrarPista2Madrid.setText("Cerrar");
        jButtonCerrarPista2Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPista2MadridActionPerformed(evt);
            }
        });

        jButtonAbrirPista2Madrid.setText("Abrir");
        jButtonAbrirPista2Madrid.setEnabled(false);
        jButtonAbrirPista2Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPista2MadridActionPerformed(evt);
            }
        });

        jLabel10.setText("Pista 3");

        jButtonCerrarPista3Madrid.setText("Cerrar");
        jButtonCerrarPista3Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPista3MadridActionPerformed(evt);
            }
        });

        jButtonAbrirPista3Madrid.setText("Abrir");
        jButtonAbrirPista3Madrid.setEnabled(false);
        jButtonAbrirPista3Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPista3MadridActionPerformed(evt);
            }
        });

        jLabel11.setText("Pista 4");

        jButtonCerrarPista4Madrid.setText("Cerrar");
        jButtonCerrarPista4Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPista4MadridActionPerformed(evt);
            }
        });

        jButtonAbrirPista4Madrid.setText("Abrir");
        jButtonAbrirPista4Madrid.setEnabled(false);
        jButtonAbrirPista4Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPista4MadridActionPerformed(evt);
            }
        });

        jTextFieldAeroviaBarcelona_Madrid.setEditable(false);

        jTextFieldAeroviaMadrid_Barcelona.setEditable(false);

        jLabel18.setText("Aerovia Madrid-Barcelona:");

        jLabel19.setText("Aerovia Barcelona-Madrid:");

        jButtonCerrarPista4Barcelona.setText("Cerrar");
        jButtonCerrarPista4Barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPista4BarcelonaActionPerformed(evt);
            }
        });

        jButtonAbrirPista4Barcelona.setText("Abrir");
        jButtonAbrirPista4Barcelona.setEnabled(false);
        jButtonAbrirPista4Barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPista4BarcelonaActionPerformed(evt);
            }
        });

        jLabel12.setText("Nº Pasajeros en Aeropuerto:");

        jTextFieldPasajerosAeropuertoBarcelona.setEditable(false);

        jLabel13.setText("Nº Aviones en Hangar:");

        jTextFieldAvionesHangarBarcelona.setEditable(false);

        jLabel14.setText("Nº Aviones en Taller:");

        jTextFieldAvionesTallerBarcelona.setEditable(false);

        jTextFieldAvionesAreaEstacionamientoBarcelona.setEditable(false);

        jLabel15.setText("Nº Aviones en Area de Estacionamiento:");

        jTextFieldAvionesAreaRodajeBarcelona.setEditable(false);

        jLabel16.setText("Nº Aviones en Area de Rodaje:");

        jLabel17.setText("Pista 1");

        jButtonCerrarPista1Barcelona.setText("Cerrar");
        jButtonCerrarPista1Barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPista1BarcelonaActionPerformed(evt);
            }
        });

        jButtonAbrirPista1Barcelona.setText("Abrir");
        jButtonAbrirPista1Barcelona.setEnabled(false);
        jButtonAbrirPista1Barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPista1BarcelonaActionPerformed(evt);
            }
        });

        jLabel20.setText("Pista 2");

        jButtonCerrarPista2Barcelona.setText("Cerrar");
        jButtonCerrarPista2Barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPista2BarcelonaActionPerformed(evt);
            }
        });

        jButtonAbrirPista2Barcelona.setText("Abrir");
        jButtonAbrirPista2Barcelona.setEnabled(false);
        jButtonAbrirPista2Barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPista2BarcelonaActionPerformed(evt);
            }
        });

        jLabel21.setText("Pista 3");

        jButtonCerrarPista3Barcelona.setText("Cerrar");
        jButtonCerrarPista3Barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPista3BarcelonaActionPerformed(evt);
            }
        });

        jButtonAbrirPista3Barcelona.setText("Abrir");
        jButtonAbrirPista3Barcelona.setEnabled(false);
        jButtonAbrirPista3Barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPista3BarcelonaActionPerformed(evt);
            }
        });

        jLabel22.setText("Pista 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldAeroviaBarcelona_Madrid))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldAeroviaMadrid_Barcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAvionesAreaEstacionamientoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPasajerosAeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAvionesHangarMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAvionesTallerMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonCerrarPista2Madrid)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonAbrirPista2Madrid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonCerrarPista1Madrid)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonAbrirPista1Madrid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonCerrarPista4Madrid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAbrirPista4Madrid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonCerrarPista3Madrid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAbrirPista3Madrid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldAvionesAreaRodajeMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAvionesAreaEstacionamientoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPasajerosAeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAvionesHangarBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAvionesTallerBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonCerrarPista2Barcelona)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonAbrirPista2Barcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonCerrarPista1Barcelona)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonAbrirPista1Barcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(53, 53, 53)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonCerrarPista4Barcelona)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAbrirPista4Barcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonCerrarPista3Barcelona)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAbrirPista3Barcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldAvionesAreaRodajeBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldPasajerosAeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldAvionesHangarMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldAvionesTallerMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldAvionesAreaEstacionamientoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldAvionesAreaRodajeMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jButtonCerrarPista1Madrid)
                                    .addComponent(jButtonAbrirPista1Madrid))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jButtonCerrarPista2Madrid)
                                    .addComponent(jButtonAbrirPista2Madrid)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jButtonCerrarPista3Madrid)
                                    .addComponent(jButtonAbrirPista3Madrid))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jButtonCerrarPista4Madrid)
                                    .addComponent(jButtonAbrirPista4Madrid)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldPasajerosAeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldAvionesHangarBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldAvionesTallerBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldAvionesAreaEstacionamientoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldAvionesAreaRodajeBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jButtonCerrarPista1Barcelona)
                                    .addComponent(jButtonAbrirPista1Barcelona))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jButtonCerrarPista2Barcelona)
                                    .addComponent(jButtonAbrirPista2Barcelona)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jButtonCerrarPista3Barcelona)
                                    .addComponent(jButtonAbrirPista3Barcelona))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jButtonCerrarPista4Barcelona)
                                    .addComponent(jButtonAbrirPista4Barcelona))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldAeroviaMadrid_Barcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldAeroviaBarcelona_Madrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarPista1MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPista1MadridActionPerformed
        // TODO add your handling code here:
        jButtonCerrarPista1Madrid.setEnabled(false);
        cliente.setPasoPistasNumero(1);
        jButtonAbrirPista1Madrid.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarPista1MadridActionPerformed

    private void jButtonCerrarPista2MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPista2MadridActionPerformed
        // TODO add your handling code here:
        jButtonCerrarPista2Madrid.setEnabled(false);
        cliente.setPasoPistasNumero(2);
        jButtonAbrirPista2Madrid.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarPista2MadridActionPerformed

    private void jButtonCerrarPista3MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPista3MadridActionPerformed
        // TODO add your handling code here:
        jButtonCerrarPista3Madrid.setEnabled(false);
        cliente.setPasoPistasNumero(3);
        jButtonAbrirPista3Madrid.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarPista3MadridActionPerformed

    private void jButtonCerrarPista4MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPista4MadridActionPerformed
        // TODO add your handling code here:
        jButtonCerrarPista4Madrid.setEnabled(false);
        cliente.setPasoPistasNumero(4);
        jButtonAbrirPista4Madrid.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarPista4MadridActionPerformed

    private void jButtonAbrirPista1MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPista1MadridActionPerformed
        // TODO add your handling code here:
        jButtonAbrirPista1Madrid.setEnabled(false);
        cliente.setPasoPistasNumero(1);
        jButtonCerrarPista1Madrid.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrirPista1MadridActionPerformed

    private void jButtonAbrirPista2MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPista2MadridActionPerformed
        // TODO add your handling code here:
        jButtonAbrirPista2Madrid.setEnabled(false);
        cliente.setPasoPistasNumero(2);
        jButtonCerrarPista2Madrid.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrirPista2MadridActionPerformed

    private void jButtonAbrirPista3MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPista3MadridActionPerformed
        // TODO add your handling code here:
        jButtonAbrirPista3Madrid.setEnabled(false);
        cliente.setPasoPistasNumero(3);
        jButtonCerrarPista3Madrid.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrirPista3MadridActionPerformed

    private void jButtonAbrirPista4MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPista4MadridActionPerformed
        // TODO add your handling code here:
        jButtonAbrirPista4Madrid.setEnabled(false);
        cliente.setPasoPistasNumero(4);
        jButtonCerrarPista4Madrid.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrirPista4MadridActionPerformed


    private void jButtonCerrarPista1BarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPista1BarcelonaActionPerformed
        // TODO add your handling code here:
        jButtonCerrarPista1Barcelona.setEnabled(false);
        cliente.setPasoPistasNumero(5);
        jButtonAbrirPista1Barcelona.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarPista1BarcelonaActionPerformed

    private void jButtonCerrarPista2BarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPista2BarcelonaActionPerformed
        // TODO add your handling code here:
        jButtonCerrarPista2Barcelona.setEnabled(false);
        cliente.setPasoPistasNumero(6);
        jButtonAbrirPista2Barcelona.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarPista2BarcelonaActionPerformed

    private void jButtonCerrarPista3BarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPista3BarcelonaActionPerformed
        // TODO add your handling code here:
        jButtonCerrarPista3Barcelona.setEnabled(false);
        cliente.setPasoPistasNumero(7);
        jButtonAbrirPista3Barcelona.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarPista3BarcelonaActionPerformed

    private void jButtonCerrarPista4BarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPista4BarcelonaActionPerformed
        // TODO add your handling code here:
        jButtonCerrarPista4Barcelona.setEnabled(false);
        cliente.setPasoPistasNumero(8);
        jButtonAbrirPista4Barcelona.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarPista4BarcelonaActionPerformed

    private void jButtonAbrirPista1BarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPista1BarcelonaActionPerformed
        // TODO add your handling code here:
        jButtonAbrirPista1Barcelona.setEnabled(false);
        cliente.setPasoPistasNumero(5);
        jButtonCerrarPista1Barcelona.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrirPista1BarcelonaActionPerformed

    private void jButtonAbrirPista2BarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPista2BarcelonaActionPerformed
        // TODO add your handling code here:
        jButtonAbrirPista2Barcelona.setEnabled(false);
        cliente.setPasoPistasNumero(6);
        jButtonCerrarPista2Barcelona.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrirPista2BarcelonaActionPerformed

    private void jButtonAbrirPista3BarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPista3BarcelonaActionPerformed
        // TODO add your handling code here:
        jButtonAbrirPista3Barcelona.setEnabled(false);
        cliente.setPasoPistasNumero(7);
        jButtonCerrarPista3Barcelona.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrirPista3BarcelonaActionPerformed

    private void jButtonAbrirPista4BarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPista4BarcelonaActionPerformed
        // TODO add your handling code here:
        jButtonAbrirPista4Barcelona.setEnabled(false);
        cliente.setPasoPistasNumero(8);
        jButtonCerrarPista4Barcelona.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrirPista4BarcelonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasAeropuerto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirPista1Barcelona;
    private javax.swing.JButton jButtonAbrirPista1Madrid;
    private javax.swing.JButton jButtonAbrirPista2Barcelona;
    private javax.swing.JButton jButtonAbrirPista2Madrid;
    private javax.swing.JButton jButtonAbrirPista3Barcelona;
    private javax.swing.JButton jButtonAbrirPista3Madrid;
    private javax.swing.JButton jButtonAbrirPista4Barcelona;
    private javax.swing.JButton jButtonAbrirPista4Madrid;
    private javax.swing.JButton jButtonCerrarPista1Barcelona;
    private javax.swing.JButton jButtonCerrarPista1Madrid;
    private javax.swing.JButton jButtonCerrarPista2Barcelona;
    private javax.swing.JButton jButtonCerrarPista2Madrid;
    private javax.swing.JButton jButtonCerrarPista3Barcelona;
    private javax.swing.JButton jButtonCerrarPista3Madrid;
    private javax.swing.JButton jButtonCerrarPista4Barcelona;
    private javax.swing.JButton jButtonCerrarPista4Madrid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAeroviaBarcelona_Madrid;
    private javax.swing.JTextField jTextFieldAeroviaMadrid_Barcelona;
    private javax.swing.JTextField jTextFieldAvionesAreaEstacionamientoBarcelona;
    private javax.swing.JTextField jTextFieldAvionesAreaEstacionamientoMadrid;
    private javax.swing.JTextField jTextFieldAvionesAreaRodajeBarcelona;
    private javax.swing.JTextField jTextFieldAvionesAreaRodajeMadrid;
    private javax.swing.JTextField jTextFieldAvionesHangarBarcelona;
    private javax.swing.JTextField jTextFieldAvionesHangarMadrid;
    private javax.swing.JTextField jTextFieldAvionesTallerBarcelona;
    private javax.swing.JTextField jTextFieldAvionesTallerMadrid;
    private javax.swing.JTextField jTextFieldPasajerosAeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldPasajerosAeropuertoMadrid;
    // End of variables declaration//GEN-END:variables
}
