/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Parte1.*;

/**
 *
 * @author ediso
 */
public class Principal extends javax.swing.JFrame {

    Paso paso = new Paso();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Main principal = new Main(jTextFieldAeroviaBarcelona_Madrid,
                jTextFieldAeroviaMadrid_Barcelona, jTextFieldAreaEstacionamientoAeropuertoBarcelona,
                jTextFieldAreaEstacionamientoAeropuertoMadrid, jTextFieldAreaRodajeAeropuertoBarcelona,
                jTextFieldAreaRodajeAeropuertoMadrid, jTextFieldGate1AeropuertoBarcelona,
                jTextFieldGate1AeropuertoMadrid, jTextFieldGate2AeropuertoBarcelona,
                jTextFieldGate2AeropuertoMadrid, jTextFieldGate3AeropuertoBarcelona,
                jTextFieldGate3AeropuertoMadrid, jTextFieldGate4AeropuertoBarcelona,
                jTextFieldGate4AeropuertoMadrid, jTextFieldGate5AeropuertoBarcelona,
                jTextFieldGate5AeropuertoMadrid, jTextFieldGate6AeropuertoBarcelona,
                jTextFieldGate6AeropuertoMadrid, jTextFieldHangarAeropuertoBarcelona,
                jTextFieldHangarAeropuertoMadrid, jTextFieldNumeroPasajerosAeropuertoBarcelona,
                jTextFieldNumeroPasajerosAeropuertoMadrid, jTextFieldPista1AeropuertoBarcelona,
                jTextFieldPista1AeropuertoMadrid, jTextFieldPista2AeropuertoBarcelona,
                jTextFieldPista2AeropuertoMadrid, jTextFieldPista3AeropuertoBarcelona,
                jTextFieldPista3AeropuertoMadrid, jTextFieldPista4AeropuertoBarcelona,
                jTextFieldPista4AeropuertoMadrid, jTextFieldTallerAeropuertoBarcelona,
                jTextFieldTallerAeropuertoMadrid, jTextFieldTransferAeropuertoAutobusBarcelona,
                jTextFieldTransferAeropuertoAutobusMadrid, jTextFieldTransferCiudadAutobusMadrid,
                jTextFieldTransferCiudadAutobusBarcelona,paso);
        principal.run();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTransferAeropuertoAutobusMadrid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTransferCiudadAutobusMadrid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumeroPasajerosAeropuertoMadrid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHangarAeropuertoMadrid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTallerAeropuertoMadrid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAreaEstacionamientoAeropuertoMadrid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldGate1AeropuertoMadrid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldGate4AeropuertoMadrid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldGate2AeropuertoMadrid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldGate5AeropuertoMadrid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldGate3AeropuertoMadrid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldGate6AeropuertoMadrid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPista1AeropuertoMadrid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPista3AeropuertoMadrid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPista2AeropuertoMadrid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldPista4AeropuertoMadrid = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldAreaRodajeAeropuertoMadrid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldAeroviaMadrid_Barcelona = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldAeroviaBarcelona_Madrid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldGate3AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldGate6AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldPista1AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldPista3AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldPista2AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldTallerAeropuertoBarcelona = new javax.swing.JTextField();
        jTextFieldPista4AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldAreaEstacionamientoAeropuertoBarcelona = new javax.swing.JTextField();
        jTextFieldAreaRodajeAeropuertoBarcelona = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldGate1AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldGate4AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldGate2AeropuertoBarcelona = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldTransferAeropuertoAutobusBarcelona = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldTransferCiudadAutobusBarcelona = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldNumeroPasajerosAeropuertoBarcelona = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldHangarAeropuertoBarcelona = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldGate5AeropuertoBarcelona = new javax.swing.JTextField();
        jButtonPausar = new javax.swing.JButton();
        jButtonReanudar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hacia Aeropuerto:");

        jTextFieldTransferAeropuertoAutobusMadrid.setEditable(false);
        jTextFieldTransferAeropuertoAutobusMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTransferAeropuertoAutobusMadridActionPerformed(evt);
            }
        });

        jLabel2.setText("Hacia Ciudad:");

        jTextFieldTransferCiudadAutobusMadrid.setEditable(false);

        jLabel3.setText("Nº de Pasajeros en Aeropuerto");

        jTextFieldNumeroPasajerosAeropuertoMadrid.setEditable(false);

        jLabel4.setText("Hangar:");

        jTextFieldHangarAeropuertoMadrid.setEditable(false);
        jTextFieldHangarAeropuertoMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHangarAeropuertoMadridActionPerformed(evt);
            }
        });

        jLabel5.setText("Taller:");

        jTextFieldTallerAeropuertoMadrid.setEditable(false);

        jLabel6.setText("Area de Estacionamiento:");

        jTextFieldAreaEstacionamientoAeropuertoMadrid.setEditable(false);
        jTextFieldAreaEstacionamientoAeropuertoMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAreaEstacionamientoAeropuertoMadridActionPerformed(evt);
            }
        });

        jLabel7.setText("Gate 1:");

        jTextFieldGate1AeropuertoMadrid.setEditable(false);

        jLabel8.setText("Gate 4:");

        jTextFieldGate4AeropuertoMadrid.setEditable(false);

        jLabel9.setText("Gate 2:");

        jTextFieldGate2AeropuertoMadrid.setEditable(false);

        jLabel10.setText("Gate 5:");

        jTextFieldGate5AeropuertoMadrid.setEditable(false);
        jTextFieldGate5AeropuertoMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGate5AeropuertoMadridActionPerformed(evt);
            }
        });

        jLabel11.setText("Gate 3:");

        jTextFieldGate3AeropuertoMadrid.setEditable(false);

        jLabel12.setText("Gate 6:");

        jTextFieldGate6AeropuertoMadrid.setEditable(false);

        jLabel13.setText("Pista 1:");

        jTextFieldPista1AeropuertoMadrid.setEditable(false);

        jLabel14.setText("Pista 3:");

        jTextFieldPista3AeropuertoMadrid.setEditable(false);
        jTextFieldPista3AeropuertoMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPista3AeropuertoMadridActionPerformed(evt);
            }
        });

        jLabel15.setText("Pista 2:");

        jTextFieldPista2AeropuertoMadrid.setEditable(false);

        jLabel16.setText("Pista 4:");

        jTextFieldPista4AeropuertoMadrid.setEditable(false);
        jTextFieldPista4AeropuertoMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPista4AeropuertoMadridActionPerformed(evt);
            }
        });

        jLabel17.setText("Area de Rodaje:");

        jTextFieldAreaRodajeAeropuertoMadrid.setEditable(false);
        jTextFieldAreaRodajeAeropuertoMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAreaRodajeAeropuertoMadridActionPerformed(evt);
            }
        });

        jLabel18.setText("Aerovia Madrid-Barcelona:");

        jTextFieldAeroviaMadrid_Barcelona.setEditable(false);

        jLabel19.setText("Aerovia Barcelona-Madrid:");

        jTextFieldAeroviaBarcelona_Madrid.setEditable(false);

        jLabel20.setText("AEROPUERTO DE MADRID");

        jLabel21.setText("Gate 3:");

        jTextFieldGate3AeropuertoBarcelona.setEditable(false);

        jLabel22.setText("Gate 6:");

        jTextFieldGate6AeropuertoBarcelona.setEditable(false);

        jLabel23.setText("Pista 1:");

        jTextFieldPista1AeropuertoBarcelona.setEditable(false);

        jLabel24.setText("Pista 3:");

        jTextFieldPista3AeropuertoBarcelona.setEditable(false);
        jTextFieldPista3AeropuertoBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPista3AeropuertoBarcelonaActionPerformed(evt);
            }
        });

        jLabel25.setText("Pista 2:");

        jTextFieldPista2AeropuertoBarcelona.setEditable(false);

        jLabel26.setText("Taller:");

        jLabel27.setText("Pista 4:");

        jTextFieldTallerAeropuertoBarcelona.setEditable(false);

        jTextFieldPista4AeropuertoBarcelona.setEditable(false);
        jTextFieldPista4AeropuertoBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPista4AeropuertoBarcelonaActionPerformed(evt);
            }
        });

        jLabel28.setText("Area de Estacionamiento:");

        jLabel29.setText("Area de Rodaje:");

        jTextFieldAreaEstacionamientoAeropuertoBarcelona.setEditable(false);
        jTextFieldAreaEstacionamientoAeropuertoBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAreaEstacionamientoAeropuertoBarcelonaActionPerformed(evt);
            }
        });

        jTextFieldAreaRodajeAeropuertoBarcelona.setEditable(false);
        jTextFieldAreaRodajeAeropuertoBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAreaRodajeAeropuertoBarcelonaActionPerformed(evt);
            }
        });

        jLabel30.setText("Gate 1:");

        jTextFieldGate1AeropuertoBarcelona.setEditable(false);

        jLabel31.setText("Gate 4:");

        jTextFieldGate4AeropuertoBarcelona.setEditable(false);

        jLabel32.setText("Gate 2:");

        jTextFieldGate2AeropuertoBarcelona.setEditable(false);

        jLabel33.setText("Hacia Aeropuerto:");

        jTextFieldTransferAeropuertoAutobusBarcelona.setEditable(false);
        jTextFieldTransferAeropuertoAutobusBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTransferAeropuertoAutobusBarcelonaActionPerformed(evt);
            }
        });

        jLabel34.setText("Hacia Ciudad:");

        jTextFieldTransferCiudadAutobusBarcelona.setEditable(false);

        jLabel35.setText("Nº de Pasajeros en Aeropuerto");

        jTextFieldNumeroPasajerosAeropuertoBarcelona.setEditable(false);

        jLabel36.setText("Hangar:");

        jTextFieldHangarAeropuertoBarcelona.setEditable(false);
        jTextFieldHangarAeropuertoBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHangarAeropuertoBarcelonaActionPerformed(evt);
            }
        });

        jLabel37.setText("AEROPUERTO DE BARCELONA");

        jLabel38.setText("Gate 5:");

        jTextFieldGate5AeropuertoBarcelona.setEditable(false);
        jTextFieldGate5AeropuertoBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGate5AeropuertoBarcelonaActionPerformed(evt);
            }
        });

        jButtonPausar.setText("Pausar");
        jButtonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPausarActionPerformed(evt);
            }
        });

        jButtonReanudar.setText("Reanudar");
        jButtonReanudar.setEnabled(false);
        jButtonReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReanudarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAeroviaBarcelona_Madrid))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAeroviaMadrid_Barcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPista1AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPista3AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPista2AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPista4AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate2AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate5AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate1AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate4AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate3AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate6AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldAreaRodajeAeropuertoMadrid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldAreaEstacionamientoAeropuertoMadrid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTallerAeropuertoMadrid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldHangarAeropuertoMadrid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNumeroPasajerosAeropuertoMadrid))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTransferAeropuertoAutobusMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTransferCiudadAutobusMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel20)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPista1AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPista3AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPista2AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPista4AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate2AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate5AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate1AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate4AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate3AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldGate6AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldAreaRodajeAeropuertoBarcelona))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldAreaEstacionamientoAeropuertoBarcelona))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTallerAeropuertoBarcelona))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldHangarAeropuertoBarcelona))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNumeroPasajerosAeropuertoBarcelona))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTransferAeropuertoAutobusBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTransferCiudadAutobusBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel37))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jButtonPausar)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonReanudar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPausar)
                    .addComponent(jButtonReanudar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldTransferAeropuertoAutobusMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldTransferCiudadAutobusMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNumeroPasajerosAeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldHangarAeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTallerAeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldAreaEstacionamientoAeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldGate1AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldGate4AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldGate2AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldGate5AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldGate3AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldGate6AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextFieldAreaRodajeAeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldPista1AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldPista3AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldPista2AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldPista4AeropuertoMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jTextFieldTransferAeropuertoAutobusBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(jTextFieldTransferCiudadAutobusBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jTextFieldNumeroPasajerosAeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jTextFieldHangarAeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jTextFieldTallerAeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jTextFieldAreaEstacionamientoAeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jTextFieldGate1AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jTextFieldGate4AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jTextFieldGate2AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(jTextFieldGate5AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldGate3AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jTextFieldGate6AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTextFieldAreaRodajeAeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextFieldPista1AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jTextFieldPista3AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldPista2AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jTextFieldPista4AeropuertoBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldAeroviaMadrid_Barcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldAeroviaBarcelona_Madrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTransferAeropuertoAutobusMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTransferAeropuertoAutobusMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTransferAeropuertoAutobusMadridActionPerformed

    private void jTextFieldHangarAeropuertoMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHangarAeropuertoMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHangarAeropuertoMadridActionPerformed

    private void jTextFieldAreaEstacionamientoAeropuertoMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAreaEstacionamientoAeropuertoMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAreaEstacionamientoAeropuertoMadridActionPerformed

    private void jTextFieldGate5AeropuertoMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGate5AeropuertoMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGate5AeropuertoMadridActionPerformed

    private void jTextFieldPista3AeropuertoMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPista3AeropuertoMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPista3AeropuertoMadridActionPerformed

    private void jTextFieldPista4AeropuertoMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPista4AeropuertoMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPista4AeropuertoMadridActionPerformed

    private void jTextFieldAreaRodajeAeropuertoMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAreaRodajeAeropuertoMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAreaRodajeAeropuertoMadridActionPerformed

    private void jTextFieldPista3AeropuertoBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPista3AeropuertoBarcelonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPista3AeropuertoBarcelonaActionPerformed

    private void jTextFieldPista4AeropuertoBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPista4AeropuertoBarcelonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPista4AeropuertoBarcelonaActionPerformed

    private void jTextFieldAreaEstacionamientoAeropuertoBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAreaEstacionamientoAeropuertoBarcelonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAreaEstacionamientoAeropuertoBarcelonaActionPerformed

    private void jTextFieldAreaRodajeAeropuertoBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAreaRodajeAeropuertoBarcelonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAreaRodajeAeropuertoBarcelonaActionPerformed

    private void jTextFieldTransferAeropuertoAutobusBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTransferAeropuertoAutobusBarcelonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTransferAeropuertoAutobusBarcelonaActionPerformed

    private void jTextFieldHangarAeropuertoBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHangarAeropuertoBarcelonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHangarAeropuertoBarcelonaActionPerformed

    private void jTextFieldGate5AeropuertoBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGate5AeropuertoBarcelonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGate5AeropuertoBarcelonaActionPerformed

    private void jButtonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPausarActionPerformed
        // TODO add your handling code here:
        paso.cerrar();
        jButtonPausar.setEnabled(false);
        jButtonReanudar.setEnabled(true);
    }//GEN-LAST:event_jButtonPausarActionPerformed

    private void jButtonReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReanudarActionPerformed
        // TODO add your handling code here:
        paso.abrir();
        jButtonReanudar.setEnabled(false);
        jButtonPausar.setEnabled(true);
    }//GEN-LAST:event_jButtonReanudarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPausar;
    private javax.swing.JButton jButtonReanudar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAeroviaBarcelona_Madrid;
    private javax.swing.JTextField jTextFieldAeroviaMadrid_Barcelona;
    private javax.swing.JTextField jTextFieldAreaEstacionamientoAeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldAreaEstacionamientoAeropuertoMadrid;
    private javax.swing.JTextField jTextFieldAreaRodajeAeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldAreaRodajeAeropuertoMadrid;
    private javax.swing.JTextField jTextFieldGate1AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldGate1AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldGate2AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldGate2AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldGate3AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldGate3AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldGate4AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldGate4AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldGate5AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldGate5AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldGate6AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldGate6AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldHangarAeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldHangarAeropuertoMadrid;
    private javax.swing.JTextField jTextFieldNumeroPasajerosAeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldNumeroPasajerosAeropuertoMadrid;
    private javax.swing.JTextField jTextFieldPista1AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldPista1AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldPista2AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldPista2AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldPista3AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldPista3AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldPista4AeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldPista4AeropuertoMadrid;
    private javax.swing.JTextField jTextFieldTallerAeropuertoBarcelona;
    private javax.swing.JTextField jTextFieldTallerAeropuertoMadrid;
    private javax.swing.JTextField jTextFieldTransferAeropuertoAutobusBarcelona;
    private javax.swing.JTextField jTextFieldTransferAeropuertoAutobusMadrid;
    private javax.swing.JTextField jTextFieldTransferCiudadAutobusBarcelona;
    private javax.swing.JTextField jTextFieldTransferCiudadAutobusMadrid;
    // End of variables declaration//GEN-END:variables
}
